server:
  port: 8090

#数据库连接配置
#courseDataSource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/course?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#    username: root
#    password: root
#testDataSource:
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
        username: root
        password: root
#          url: jdbc:oracle:thin:@//localhost:1521/orcl
#          username: system
#          password: system
#          driver-class-name: oracle.jdbc.driver.OracleDriver

#testDataSource:
#    url: jdbc:oracle:thin:@//localhost:1521/orcl
#    username: system
#    password: system
#    driver-class-name: oracle.jdbc.driver.OracleDriver

#testDataSource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#    username: root
#    password: root

mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.sunyard.bigdata.pojo
    mapper-locations: classpath:mybatis/mapper/*.xml
     #    mapper-locations: classpath*:mybatis/**/*Mapper.xml
